postgres:
  image: postgres:9
  volumes:
    - /var/lib/postgresql/data

redis:
  image: redis:3

django:
  build: .
  links:
    - postgres
    - redis
  ports:
    - "8000:8000"
  command: /gunicorn.sh

celeryworker:
  build: .
  links:
   - postgres
   - redis
  command: celery -A tickle.common.celery.apps worker -l INFO

celerybeat:
  build: .
  links:
    - postgres
    - redis
  command: celery -A tickle.common.celery.apps beat -l INFO
