postgres_data:
  image: postgres:9
  volumes:
    - /var/lib/postgresql/data
  command: /bin/true

postgres:
  image: postgres:9
  volumes_from:
    - postgres_data
  env_file: .env

redis:
  image: redis:3

django:
  build: .
  links:
    - postgres
    - redis
  ports:
    - "8000:8000"
  command: /gunicorn.sh
  env_file: .env

celeryworker:
  build: .
  env_file: .env
  links:
   - postgres
   - redis
  command: celery -A tickle.common.celery.apps worker -l INFO

celerybeat:
  build: .
  env_file: .env
  links:
    - postgres
    - redis
  command: celery -A tickle.common.celery.apps beat -l INFO
